name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    uses: kurocado-studio/styleguide/.github/workflows/workflow.lint.yml@main
    secrets: inherit

  document:
    needs: lint
    uses: kurocado-studio/styleguide/.github/workflows/workflow.document.yml@main
    secrets: inherit
